import type {
  ActivityPost,
  ClassActivity,
  FinanceSummary,
  KasEntry,
  PresenceRecord,
  SchoolClass,
  SchoolDayOff,
  SchoolEvent,
  Student,
  StudentReport,
  Teacher,
  TuitionRecord,
} from "./types";

export const teachers: Teacher[] = [
  {
    id: "t1",
    name: "Maya Santoso",
    email: "maya@babelkids.id",
    phone: "+62 812-1000-1001",
    role: "owner",
    createdAt: "2024-01-10",
  },
  {
    id: "t2",
    name: "Rina Wijaya",
    email: "rina@babelkids.id",
    phone: "+62 812-1000-1002",
    role: "admin",
    createdAt: "2024-03-01",
  },
  {
    id: "t3",
    name: "Dewi Kartika",
    email: "dewi@babelkids.id",
    phone: "+62 812-1000-1003",
    role: "teacher",
    notes: "Wali kelas Little Sprouts",
    createdAt: "2024-06-15",
  },
  {
    id: "t4",
    name: "Andi Pratama",
    email: "andi@babelkids.id",
    phone: "+62 812-1000-1004",
    role: "teacher",
    notes: "Wali kelas Curious Minds",
    createdAt: "2024-08-20",
  },
  {
    id: "t5",
    name: "Budi Santoso",
    email: "budi@babelkids.id",
    phone: "+62 812-1000-1005",
    role: "teacher",
    notes: "Olahraga & outdoor",
    createdAt: "2025-01-12",
  },
  {
    id: "t6",
    name: "Sari Melati",
    email: "sari.guru@babelkids.id",
    phone: "+62 812-1000-1006",
    role: "teacher",
    notes: "Wali kelas Explorer Path",
    createdAt: "2025-02-01",
  },
];

export const classes: SchoolClass[] = [
  {
    id: "c1",
    name: "Little Sprouts",
    level: "preschool",
    teacherId: "t3",
    capacity: 12,
    room: "Room A",
    schedule: "Mon–Fri 08:00–12:00",
    ageMinYears: 2,
    ageMaxYears: 3,
  },
  {
    id: "c2",
    name: "Bright Stars",
    level: "preschool",
    teacherId: "t3",
    capacity: 14,
    room: "Room B",
    schedule: "Mon–Fri 08:00–12:00",
    ageMinYears: 3,
    ageMaxYears: 4,
  },
  {
    id: "c3",
    name: "Curious Minds",
    level: "kindergarten",
    teacherId: "t4",
    capacity: 16,
    room: "Room C",
    schedule: "Mon–Fri 08:00–14:00",
    ageMinYears: 4,
    ageMaxYears: 5,
  },
  {
    id: "c4",
    name: "Explorer Path",
    level: "kindergarten",
    teacherId: "t4",
    capacity: 16,
    room: "Room D",
    schedule: "Mon–Fri 08:00–14:00",
    ageMinYears: 5,
    ageMaxYears: 6,
  },
];

export const students: Student[] = [
  {
    id: "s1",
    name: "Alya Putri Rahman",
    nickname: "Alya",
    dateOfBirth: "2021-03-14",
    gender: "female",
    classId: "c1",
    status: "active",
    enrollmentDate: "2024-07-01",
    photoColor: "#F4A261",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s1-1",
        classId: "c2",
        className: "Bright Stars",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2024-07-01",
        endDate: "2025-06-30",
        note: "Moved for schedule fit",
      },
      {
        id: "ch-s1-2",
        classId: "c1",
        className: "Little Sprouts",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2025-07-01",
      },
    ],
    parents: [
      {
        id: "p1",
        name: "Sari Rahman",
        relationship: "mother",
        phone: "+62 811-2222-3333",
        email: "sari.rahman@email.com",
      },
      {
        id: "p1b",
        name: "Budi Rahman",
        relationship: "father",
        phone: "+62 811-2222-3334",
        email: "budi.rahman@email.com",
      },
    ],
  },
  {
    id: "s9",
    name: "Rafi Putra Rahman",
    nickname: "Rafi",
    dateOfBirth: "2019-08-05",
    gender: "male",
    classId: "c3",
    status: "active",
    enrollmentDate: "2023-07-01",
    photoColor: "#00B894",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s9-1",
        classId: "c1",
        className: "Little Sprouts",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2023-07-01",
        endDate: "2025-06-30",
      },
      {
        id: "ch-s9-2",
        classId: "c3",
        className: "Curious Minds",
        level: "kindergarten",
        teacherName: "Andi Pratama",
        startDate: "2025-07-01",
      },
    ],
    parents: [
      {
        id: "p1",
        name: "Sari Rahman",
        relationship: "mother",
        phone: "+62 811-2222-3333",
        email: "sari.rahman@email.com",
      },
      {
        id: "p1b",
        name: "Budi Rahman",
        relationship: "father",
        phone: "+62 811-2222-3334",
        email: "budi.rahman@email.com",
      },
    ],
  },
  {
    id: "s2",
    name: "Kenzo Aditya",
    nickname: "Kenzo",
    dateOfBirth: "2020-11-02",
    gender: "male",
    classId: "c1",
    status: "active",
    enrollmentDate: "2024-07-01",
    photoColor: "#2A9D8F",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s2-1",
        classId: "c1",
        className: "Little Sprouts",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p2",
        name: "Lisa Aditya",
        relationship: "mother",
        phone: "+62 811-3333-4444",
        email: "lisa.aditya@email.com",
      },
    ],
  },
  {
    id: "s3",
    name: "Mika Anggraini",
    nickname: "Mika",
    dateOfBirth: "2021-07-22",
    gender: "female",
    classId: "c2",
    status: "active",
    enrollmentDate: "2024-08-15",
    photoColor: "#E76F51",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s3-1",
        classId: "c2",
        className: "Bright Stars",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p3",
        name: "Nina Anggraini",
        relationship: "mother",
        phone: "+62 811-4444-5555",
        email: "nina.ang@email.com",
      },
    ],
  },
  {
    id: "s4",
    name: "Raka Firmansyah",
    nickname: "Raka",
    dateOfBirth: "2020-05-08",
    gender: "male",
    classId: "c2",
    status: "active",
    enrollmentDate: "2024-07-01",
    photoColor: "#457B9D",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s4-1",
        classId: "c2",
        className: "Bright Stars",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p4",
        name: "Hendra Firmansyah",
        relationship: "father",
        phone: "+62 811-5555-6666",
        email: "hendra.f@email.com",
      },
    ],
  },
  {
    id: "s5",
    name: "Sofia Chen",
    nickname: "Sofia",
    dateOfBirth: "2019-09-30",
    gender: "female",
    classId: "c3",
    status: "active",
    enrollmentDate: "2023-07-01",
    photoColor: "#9B5DE5",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s5-1",
        classId: "c2",
        className: "Bright Stars",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2023-07-01",
        endDate: "2024-06-30",
      },
      {
        id: "ch-s5-2",
        classId: "c3",
        className: "Curious Minds",
        level: "kindergarten",
        teacherName: "Andi Pratama",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p5",
        name: "Mei Chen",
        relationship: "mother",
        phone: "+62 811-6666-7777",
        email: "mei.chen@email.com",
      },
    ],
  },
  {
    id: "s6",
    name: "Arjun Patel",
    nickname: "Arjun",
    dateOfBirth: "2019-12-12",
    gender: "male",
    classId: "c3",
    status: "active",
    enrollmentDate: "2023-07-01",
    photoColor: "#00BBF9",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s6-1",
        classId: "c1",
        className: "Little Sprouts",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2023-07-01",
        endDate: "2024-06-30",
      },
      {
        id: "ch-s6-2",
        classId: "c3",
        className: "Curious Minds",
        level: "kindergarten",
        teacherName: "Andi Pratama",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p6",
        name: "Priya Patel",
        relationship: "mother",
        phone: "+62 811-7777-8888",
        email: "priya.p@email.com",
      },
    ],
  },
  {
    id: "s7",
    name: "Elena Putri",
    nickname: "Elena",
    dateOfBirth: "2019-04-18",
    gender: "female",
    classId: "c4",
    status: "active",
    enrollmentDate: "2023-08-01",
    photoColor: "#F15BB5",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s7-1",
        classId: "c1",
        className: "Little Sprouts",
        level: "preschool",
        teacherName: "Dewi Kartika",
        startDate: "2023-07-01",
        endDate: "2024-06-30",
      },
      {
        id: "ch-s7-2",
        classId: "c4",
        className: "Explorer Path",
        level: "kindergarten",
        teacherName: "Andi Pratama",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p7",
        name: "Wulan Putri",
        relationship: "mother",
        phone: "+62 811-8888-9999",
        email: "wulan.putri@email.com",
      },
    ],
  },
  {
    id: "s8",
    name: "Leo Santoso",
    nickname: "Leo",
    dateOfBirth: "2020-01-25",
    gender: "male",
    classId: "c4",
    status: "inactive",
    enrollmentDate: "2024-01-10",
    photoColor: "#FEE440",
    allergies: "None known",
    notes: "",
    classHistory: [
      {
        id: "ch-s8-1",
        classId: "c4",
        className: "Explorer Path",
        level: "kindergarten",
        teacherName: "Andi Pratama",
        startDate: "2024-07-01",
      },
    ],
    parents: [
      {
        id: "p8",
        name: "Agus Santoso",
        relationship: "father",
        phone: "+62 811-9999-0000",
        email: "agus.s@email.com",
      },
    ],
  },
];

export const tuitionRecords: TuitionRecord[] = [
  {
    id: "tu1",
    studentId: "s1",
    month: "2026-07",
    amount: 2500000,
    status: "paid",
    dueDate: "2026-07-05",
    paidAt: "2026-07-02",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
  },
  {
    id: "tu2",
    studentId: "s2",
    month: "2026-07",
    amount: 2500000,
    status: "submitted",
    dueDate: "2026-07-05",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
    proofStatus: "pending",
    note: "Transfer BCA 02 Jul",
  },
  {
    id: "tu3",
    studentId: "s3",
    month: "2026-07",
    amount: 2500000,
    status: "pending",
    dueDate: "2026-07-05",
  },
  {
    id: "tu4",
    studentId: "s4",
    month: "2026-07",
    amount: 2500000,
    status: "overdue",
    dueDate: "2026-07-05",
  },
  {
    id: "tu5",
    studentId: "s5",
    month: "2026-07",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-07-05",
    paidAt: "2026-07-01",
    paymentMethod: "tunai",
    proofStatus: "approved",
    note: "Bayar tunai di sekolah",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "tu6",
    studentId: "s6",
    month: "2026-07",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-07-05",
    paidAt: "2026-06-28",
    paymentMethod: "whatsapp",
    proofStatus: "approved",
    note: "Konfirmasi via WA ke Bu Maya",
    recordedBy: "Maya Santoso",
  },
  {
    id: "tu7",
    studentId: "s7",
    month: "2026-07",
    amount: 2800000,
    status: "submitted",
    dueDate: "2026-07-05",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80",
    proofStatus: "pending",
  },
  {
    id: "tu8",
    studentId: "s1",
    month: "2026-06",
    amount: 2500000,
    status: "paid",
    dueDate: "2026-06-05",
    paidAt: "2026-06-03",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
  },
  {
    id: "tu9",
    studentId: "s2",
    month: "2026-06",
    amount: 2500000,
    status: "paid",
    dueDate: "2026-06-05",
    paidAt: "2026-06-04",
    paymentMethod: "tunai",
    proofStatus: "approved",
    recordedBy: "Dewi Kartika",
  },
  {
    id: "tu10",
    studentId: "s5",
    month: "2026-06",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-06-05",
    paidAt: "2026-06-01",
    paymentMethod: "transfer",
    proofStatus: "approved",
  },
  {
    id: "tu11",
    studentId: "s1",
    month: "2026-05",
    amount: 2500000,
    status: "paid",
    dueDate: "2026-05-05",
    paidAt: "2026-05-02",
    paymentMethod: "whatsapp",
    proofUrl:
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
    note: "Kirim bukti via WA",
    recordedBy: "Maya Santoso",
  },
  {
    id: "tu12",
    studentId: "s9",
    month: "2026-07",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-07-05",
    paidAt: "2026-07-03",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
  },
  {
    id: "tu13",
    studentId: "s9",
    month: "2026-06",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-06-05",
    paidAt: "2026-06-02",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
  },
  {
    id: "tu14",
    studentId: "s1",
    month: "2025-12",
    amount: 2500000,
    status: "paid",
    dueDate: "2025-12-05",
    paidAt: "2025-12-01",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
  },
  {
    id: "tu15",
    studentId: "s9",
    month: "2025-11",
    amount: 2800000,
    status: "paid",
    dueDate: "2025-11-05",
    paidAt: "2025-11-03",
    paymentMethod: "tunai",
    proofStatus: "approved",
    note: "Bayar tunai di sekolah",
  },
  /* Last 2 months (Aug–Sep 2026) */
  {
    id: "tu16",
    studentId: "s1",
    month: "2026-08",
    amount: 2500000,
    status: "paid",
    dueDate: "2026-08-05",
    paidAt: "2026-08-02",
    paymentMethod: "transfer",
    proofUrl:
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
    note: "Transfer BCA a.n. Sari Rahman",
  },
  {
    id: "tu17",
    studentId: "s1",
    month: "2026-09",
    amount: 2500000,
    status: "pending",
    dueDate: "2026-09-05",
  },
  {
    id: "tu18",
    studentId: "s9",
    month: "2026-08",
    amount: 2800000,
    status: "paid",
    dueDate: "2026-08-05",
    paidAt: "2026-08-01",
    paymentMethod: "whatsapp",
    proofUrl:
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80",
    proofStatus: "approved",
    note: "Konfirmasi via WA",
    recordedBy: "Maya Santoso",
  },
  {
    id: "tu19",
    studentId: "s9",
    month: "2026-09",
    amount: 2800000,
    status: "pending",
    dueDate: "2026-09-05",
  },
];

export const classActivities: ClassActivity[] = [
  {
    id: "ca1",
    classId: "c1",
    title: "Seni lukis jari",
    description:
      "Anak-anak mengeksplor warna primer lewat finger painting. Karya dipajang di dinding kelas. Setiap anak mencoba mencampur kuning, biru, dan merah sampai menemukan warna favoritnya.",
    date: "2026-09-15",
    teacherName: "Bu Dewi",
    location: "Ruang Seni",
    images: [
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
    ],
    videoUrl:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "ca2",
    classId: "c1",
    title: "Cerita bilingual pagi",
    description:
      "Circle time dengan buku cerita English–Bahasa. Alya ikut membaca baris terakhir! Kelas berlatih kosakata hewan dan menyanyi lagu pendek bersama.",
    date: "2026-09-14",
    teacherName: "Bu Dewi",
    location: "Circle Time",
    images: [
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca3",
    classId: "c3",
    title: "Eksperimen air & minyak",
    description:
      "Curious Minds mencoba eksperimen sederhana di lab mini. Diskusi sains yang seru tentang densitas dan warna.",
    date: "2026-09-15",
    teacherName: "Pak Andi",
    location: "Lab Mini",
    images: [
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=800&q=80",
    ],
    videoUrl:
      "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "ca4",
    classId: "c1",
    title: "Taman sayur mini",
    description:
      "Menanam bibit sawi di pot kelas. Setiap anak punya pot berlabel nama dan belajar menyiram dengan takaran kecil.",
    date: "2026-09-12",
    teacherName: "Bu Dewi",
    location: "Kebun Sekolah",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80",
    ],
  },
  {
    id: "ca5",
    classId: "c1",
    title: "Musik & gerak",
    description:
      "Senam pagi dengan lagu bilingual. Anak berlatih mengikuti irama, bertepuk tangan, dan berganti posisi dalam lingkaran.",
    date: "2026-09-16",
    teacherName: "Bu Dewi",
    location: "Aula kecil",
    images: [
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca6",
    classId: "c1",
    title: "Snack sehat bersama",
    description:
      "Menyiapkan potongan buah dan sandwich mini. Anak belajar mencuci tangan, berbagi, dan menyebut nama buah dalam dua bahasa.",
    date: "2026-09-10",
    teacherName: "Bu Rina",
    location: "Meja makan kelas",
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca7",
    classId: "c2",
    title: "Blok bangunan raksasa",
    description:
      "Bright Stars membangun kota mini dari balok kayu. Diskusi tentang rumah, jalan, dan siapa tinggal di mana.",
    date: "2026-09-15",
    teacherName: "Bu Maya",
    location: "Area bermain dalam",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca8",
    classId: "c2",
    title: "Lukis dengan spons",
    description:
      "Teknik stempel spons untuk membuat langit dan awan. Karya dikeringkan di rak jendela kelas.",
    date: "2026-09-11",
    teacherName: "Bu Maya",
    location: "Ruang Seni",
    images: [
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca9",
    classId: "c2",
    title: "Kunjungan ke perpustakaan mini",
    description:
      "Memilih buku favorit dan mendengarkan bacaan singkat. Setiap anak meminjam satu buku bergambar untuk dibawa pulang akhir pekan.",
    date: "2026-09-08",
    teacherName: "Bu Rina",
    location: "Perpustakaan",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca10",
    classId: "c3",
    title: "Peta kelas 3D",
    description:
      "Membuat denah kelas dari kertas dan stik es krim. Melatih arah kiri-kanan dan posisi meja teman.",
    date: "2026-09-16",
    teacherName: "Pak Andi",
    location: "Kelas Curious Minds",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca11",
    classId: "c3",
    title: "Olahraga lempar tangkap",
    description:
      "Permainan bola lembut di lapangan. Fokus koordinasi mata-tangan dan bergiliran dalam tim kecil.",
    date: "2026-09-09",
    teacherName: "Pak Budi",
    location: "Lapangan",
    images: [
      "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca12",
    classId: "c4",
    title: "Eksplorasi magnit",
    description:
      "Explorer Path menguji benda mana yang menempel pada magnet. Catatan sederhana di lembar kerja.",
    date: "2026-09-15",
    teacherName: "Bu Sari",
    location: "Lab Mini",
    images: [
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca13",
    classId: "c4",
    title: "Drama peran pasar",
    description:
      "Anak berperan sebagai penjual dan pembeli di pasar mini. Latihan percakapan sopan dan berhitung uang mainan.",
    date: "2026-09-12",
    teacherName: "Bu Sari",
    location: "Sudut bermain peran",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca14",
    classId: "c1",
    title: "Kolase daun kering",
    description:
      "Mengumpulkan daun di kebun lalu menempelkannya menjadi hewan imajiner. Latihan gunting aman dengan bantuan guru.",
    date: "2026-08-28",
    teacherName: "Bu Dewi",
    location: "Kebun & Ruang Seni",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca15",
    classId: "c1",
    title: "Hari mandiri tali sepatu",
    description:
      "Latihan mengikat tali sepatu dan merapikan tas. Anak yang sudah mahir membantu teman sebangku.",
    date: "2026-08-25",
    teacherName: "Bu Rina",
    location: "Kelas Little Sprouts",
    images: [
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca16",
    classId: "c2",
    title: "Parade kostum hewan",
    description:
      "Anak memakai topi hewan buatan sendiri dan menceritakan suara serta habitatnya di depan kelas.",
    date: "2026-08-22",
    teacherName: "Bu Maya",
    location: "Aula kecil",
    images: [
      "https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca17",
    classId: "c3",
    title: "Menulis jurnal cuaca",
    description:
      "Mengamati langit pagi dan mencatat cuaca dengan simbol gambar. Membandingkan dengan hari sebelumnya.",
    date: "2026-08-20",
    teacherName: "Pak Andi",
    location: "Teras kelas",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca18",
    classId: "c4",
    title: "Proyek jembatan sedotan",
    description:
      "Kerja kelompok membuat jembatan dari sedotan dan isolasi. Uji kekuatan dengan mainan kecil.",
    date: "2026-08-18",
    teacherName: "Bu Sari",
    location: "Lab Mini",
    images: [
      "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80",
    ],
  },
  /* Sep 17–23 2026 (until today) */
  {
    id: "ca19",
    classId: "c1",
    title: "Puzzle huruf raksasa",
    description:
      "Menyusun huruf besar jadi nama masing-masing. Alya membantu Kenzo menemukan huruf K.",
    date: "2026-09-17",
    teacherName: "Bu Dewi",
    location: "Circle Time",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588072432836-e10032774350?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca20",
    classId: "c2",
    title: "Masak pura-pura sayur",
    description:
      "Roleplay dapur dengan sayuran plastik. Latihan kosakata makanan dan bergiliran jadi koki.",
    date: "2026-09-17",
    teacherName: "Bu Maya",
    location: "Sudut bermain peran",
    images: [
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca21",
    classId: "c1",
    title: "Jalan sehat di halaman",
    description:
      "Jalan kaki mengelilingi taman sekolah sambil menghitung langkah. Fokus keseimbangan dan aturan antre.",
    date: "2026-09-18",
    teacherName: "Bu Rina",
    location: "Halaman depan",
    images: [
      "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca22",
    classId: "c3",
    title: "Presentasi hewan favorit",
    description:
      "Setiap anak membawa gambar hewan dan bercerita 1 menit. Melatih percaya diri di depan kelas.",
    date: "2026-09-18",
    teacherName: "Pak Andi",
    location: "Kelas Curious Minds",
    images: [
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca23",
    classId: "c1",
    title: "Senin cerita pendek",
    description:
      "Membuka minggu dengan dongeng bilingual. Anak menebak akhir cerita dan menggambar tokoh favorit.",
    date: "2026-09-21",
    teacherName: "Bu Dewi",
    location: "Circle Time",
    images: [
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca24",
    classId: "c4",
    title: "Ukur tinggi tanaman",
    description:
      "Mengukur bibit di kebun dengan penggaris. Mencatat angka di lembar observasi sederhana.",
    date: "2026-09-21",
    teacherName: "Bu Sari",
    location: "Kebun Sekolah",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca25",
    classId: "c1",
    title: "Kolase bentuk geometri",
    description:
      "Menempel lingkaran, segitiga, dan persegi jadi wajah lucu. Latihan gunting dan lem aman.",
    date: "2026-09-22",
    teacherName: "Bu Dewi",
    location: "Ruang Seni",
    images: [
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca26",
    classId: "c2",
    title: "Lagu angka 1–10",
    description:
      "Bernyanyi sambil bertepuk sesuai angka. Bright Stars berlatih mengurutkan kartu angka di lantai.",
    date: "2026-09-22",
    teacherName: "Bu Maya",
    location: "Aula kecil",
    images: [
      "https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca27",
    classId: "c3",
    title: "Percobaan bayangan",
    description:
      "Menggunakan senter dan boneka untuk melihat bayangan berubah. Diskusi tentang cahaya dan gelap.",
    date: "2026-09-22",
    teacherName: "Pak Andi",
    location: "Lab Mini",
    images: [
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca28",
    classId: "c1",
    title: "Hari berbagi mainan",
    description:
      "Setiap anak membawa satu mainan kecil untuk digilir. Melatih menunggu giliran dan mengucapkan terima kasih.",
    date: "2026-09-23",
    teacherName: "Bu Dewi",
    location: "Kelas Little Sprouts",
    images: [
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca29",
    classId: "c3",
    title: "Menulis surat untuk orang tua",
    description:
      "Anak menggambar dan menempel stiker di kartu kecil untuk dibawa pulang. Rafi menulis nama sendiri.",
    date: "2026-09-23",
    teacherName: "Pak Andi",
    location: "Kelas Curious Minds",
    images: [
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "ca30",
    classId: "c4",
    title: "Rangkaian lampu sederhana",
    description:
      "Mencoba rangkaian baterai dan bohlam mini. Explorer Path mengamati kapan lampu menyala.",
    date: "2026-09-23",
    teacherName: "Bu Sari",
    location: "Lab Mini",
    images: [
      "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80",
    ],
  },
];

export function classActivitiesFor(classId: string) {
  return classActivities
    .filter((a) => a.classId === classId)
    .sort((a, b) => b.date.localeCompare(a.date));
}

export function getClassActivity(id: string) {
  return classActivities.find((a) => a.id === id);
}

export const activityPosts: ActivityPost[] = [
  {
    id: "a1",
    eventId: "e3",
    eventName: "Storytelling Carnival",
    description:
      "Costumes, puppet shows, and bilingual story circles celebrating imagination across every classroom.",
    date: "2026-06-20",
    images: [
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "a2",
    eventId: "e4",
    eventName: "Field Trip: Mini Zoo",
    description:
      "A sunny half-day with animal feeding, nature walks, and picnic laughs under the trees.",
    date: "2026-05-15",
    images: [
      "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1425082661705-1834bfd09dca?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1535268647677-300dbf3d78d1?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "a3",
    eventId: "e1",
    eventName: "Garden Discovery Day",
    description:
      "Hands-on garden stations — planting seeds, spotting insects, and muddy giggles outdoors.",
    date: "2026-07-28",
    images: [
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80",
    ],
  },
  {
    id: "a4",
    eventId: "e2",
    eventName: "Parents & Kids Cooking",
    description:
      "Families cook simple Indonesian snacks together in the activity hall — aprons welcome.",
    date: "2026-08-10",
    images: [
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=800&q=80",
    ],
  },
];

export const events: SchoolEvent[] = [
  {
    id: "e1",
    title: "Garden Discovery Day",
    description:
      "Kids explore our outdoor garden, plant seeds, and learn about insects with hands-on stations.",
    date: "2026-07-28",
    location: "School Garden",
    feePerChild: 75000,
    status: "upcoming",
    coverGradient: "linear-gradient(135deg, #2A9D8F 0%, #E9C46A 100%)",
    coverImage:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=1200&q=80",
    attendees: ["s1", "s2", "s3", "s5", "s9"],
    documentation: [],
  },
  {
    id: "e2",
    title: "Parents & Kids Cooking",
    description:
      "A fun morning cooking simple Indonesian snacks together in the activity hall.",
    date: "2026-08-10",
    location: "Activity Hall",
    feePerChild: 120000,
    status: "upcoming",
    coverGradient: "linear-gradient(135deg, #E76F51 0%, #F4A261 100%)",
    coverImage:
      "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=1200&q=80",
    attendees: ["s1", "s4", "s6", "s7", "s9"],
    documentation: [],
  },
  {
    id: "e3",
    title: "Storytelling Carnival",
    description:
      "Costumes, puppet shows, and bilingual story circles celebrating imagination.",
    date: "2026-06-20",
    endDate: "2026-06-20",
    location: "Main Hall",
    feePerChild: 50000,
    status: "past",
    coverGradient: "linear-gradient(135deg, #457B9D 0%, #A8DADC 100%)",
    coverImage:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1200&q=80",
    attendees: ["s1", "s2", "s3", "s4", "s5", "s6", "s7", "s9"],
    documentation: [
      {
        id: "d1",
        caption: "Alya opening the puppet show",
        type: "photo",
        color: "#F4A261",
        imageUrl:
          "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80",
        createdAt: "2026-06-20T10:00:00",
      },
      {
        id: "d2",
        caption: "Group reading circle in Room C",
        type: "photo",
        color: "#2A9D8F",
        imageUrl:
          "https://images.unsplash.com/photo-1596464716127-f2a82984de30?auto=format&fit=crop&w=800&q=80",
        createdAt: "2026-06-20T11:00:00",
      },
      {
        id: "d3",
        caption: "Everyone loved the bilingual stories!",
        type: "note",
        color: "#E9C46A",
        imageUrl:
          "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80",
        createdAt: "2026-06-20T14:00:00",
      },
    ],
  },
  {
    id: "e4",
    title: "Field Trip: Mini Zoo",
    description: "Half-day visit to the mini zoo with animal feeding and nature walk.",
    date: "2026-05-15",
    location: "City Mini Zoo",
    feePerChild: 200000,
    status: "past",
    coverGradient: "linear-gradient(135deg, #264653 0%, #2A9D8F 100%)",
    coverImage:
      "https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=1200&q=80",
    attendees: ["s1", "s2", "s5", "s6", "s7", "s9"],
    documentation: [
      {
        id: "d4",
        caption: "Feeding the goats",
        type: "photo",
        color: "#E76F51",
        imageUrl:
          "https://images.unsplash.com/photo-1535268647677-300dbf3d78d1?auto=format&fit=crop&w=800&q=80",
        createdAt: "2026-05-15T09:30:00",
      },
      {
        id: "d5",
        caption: "Picnic lunch under the trees",
        type: "photo",
        color: "#457B9D",
        imageUrl:
          "https://images.unsplash.com/photo-1476703993599-0035a21b17a9?auto=format&fit=crop&w=800&q=80",
        createdAt: "2026-05-15T12:00:00",
      },
    ],
  },
];

export const schoolDayOffs: SchoolDayOff[] = [
  {
    id: "off1",
    date: "2026-08-17",
    title: "Hari Kemerdekaan RI",
    description: "Libur nasional — sekolah tutup.",
    type: "holiday",
  },
  {
    id: "off2",
    date: "2026-07-24",
    title: "Rapat guru",
    description: "Siswa libur, guru ada briefing kurikulum.",
    type: "school_off",
  },
  {
    id: "off3",
    date: "2026-09-16",
    title: "Libur bersama",
    description: "Libur bersama setelah cuti bersama nasional.",
    type: "other",
  },
];

export function getDayOff(date: string, offs: SchoolDayOff[] = schoolDayOffs) {
  return offs.find((o) => o.date === date);
}

/** Saturday (6) or Sunday (0) */
export function isWeekend(dateIso: string): boolean {
  const d = new Date(`${dateIso}T12:00:00`);
  const day = d.getDay();
  return day === 0 || day === 6;
}

export function isSchoolClosed(
  dateIso: string,
  offs: SchoolDayOff[] = schoolDayOffs,
): boolean {
  return isWeekend(dateIso) || Boolean(getDayOff(dateIso, offs));
}

export const presenceRecords: PresenceRecord[] = [
  {
    id: "pr1",
    studentId: "s1",
    classId: "c1",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr2",
    studentId: "s2",
    classId: "c1",
    date: "2026-07-21",
    status: "late",
    note: "Arrived 08:25",
    recordedBy: "t3",
  },
  {
    id: "pr3",
    studentId: "s3",
    classId: "c2",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr4",
    studentId: "s4",
    classId: "c2",
    date: "2026-07-21",
    status: "absent",
    note: "Sick leave",
    recordedBy: "t3",
  },
  {
    id: "pr5",
    studentId: "s5",
    classId: "c3",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr6",
    studentId: "s6",
    classId: "c3",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr7",
    studentId: "s7",
    classId: "c4",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr11",
    studentId: "s9",
    classId: "c3",
    date: "2026-07-21",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr12",
    studentId: "s9",
    classId: "c3",
    date: "2026-07-18",
    status: "late",
    note: "Traffic",
    recordedBy: "t4",
  },
  {
    id: "pr8",
    studentId: "s1",
    classId: "c1",
    date: "2026-07-18",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr9",
    studentId: "s1",
    classId: "c1",
    date: "2026-07-17",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr10",
    studentId: "s1",
    classId: "c1",
    date: "2026-07-16",
    status: "excused",
    note: "Family event",
    recordedBy: "t3",
  },
  {
    id: "pr13",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-15",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr14",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-12",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr15",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-11",
    status: "absent",
    note: "Demam",
    recordedBy: "t3",
  },
  {
    id: "pr16",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-10",
    status: "excused",
    note: "Kontrol dokter",
    recordedBy: "t3",
  },
  {
    id: "pr17",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-09",
    status: "late",
    recordedBy: "t3",
  },
  {
    id: "pr18",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-08",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr19",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-15",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr20",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-12",
    status: "absent",
    recordedBy: "t4",
  },
  {
    id: "pr21",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-11",
    status: "present",
    recordedBy: "t4",
  },
  /* Sep 17–23 2026 */
  {
    id: "pr22",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-17",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr23",
    studentId: "s2",
    classId: "c1",
    date: "2026-09-17",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr24",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-17",
    status: "late",
    note: "Hujan",
    recordedBy: "t4",
  },
  {
    id: "pr25",
    studentId: "s5",
    classId: "c3",
    date: "2026-09-17",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr26",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-18",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr27",
    studentId: "s2",
    classId: "c1",
    date: "2026-09-18",
    status: "excused",
    note: "Kontrol gigi",
    recordedBy: "t3",
  },
  {
    id: "pr28",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-18",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr29",
    studentId: "s7",
    classId: "c4",
    date: "2026-09-18",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr30",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-21",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr31",
    studentId: "s2",
    classId: "c1",
    date: "2026-09-21",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr32",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-21",
    status: "absent",
    note: "Flu",
    recordedBy: "t4",
  },
  {
    id: "pr33",
    studentId: "s3",
    classId: "c2",
    date: "2026-09-21",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr34",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-22",
    status: "late",
    note: "Macet",
    recordedBy: "t3",
  },
  {
    id: "pr35",
    studentId: "s2",
    classId: "c1",
    date: "2026-09-22",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr36",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-22",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr37",
    studentId: "s5",
    classId: "c3",
    date: "2026-09-22",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr38",
    studentId: "s4",
    classId: "c2",
    date: "2026-09-22",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr39",
    studentId: "s1",
    classId: "c1",
    date: "2026-09-23",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr40",
    studentId: "s2",
    classId: "c1",
    date: "2026-09-23",
    status: "present",
    recordedBy: "t3",
  },
  {
    id: "pr41",
    studentId: "s9",
    classId: "c3",
    date: "2026-09-23",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr42",
    studentId: "s5",
    classId: "c3",
    date: "2026-09-23",
    status: "late",
    recordedBy: "t4",
  },
  {
    id: "pr43",
    studentId: "s7",
    classId: "c4",
    date: "2026-09-23",
    status: "present",
    recordedBy: "t4",
  },
  {
    id: "pr44",
    studentId: "s8",
    classId: "c4",
    date: "2026-09-23",
    status: "present",
    recordedBy: "t4",
  },
];

export const studentReports: StudentReport[] = [
  {
    id: "r1",
    studentId: "s1",
    teacherId: "t3",
    date: "2026-07-18",
    title: "Weekly progress",
    mood: "happy",
    activities: "Circle time, sensory play with sand, outdoor climbing.",
    meals: "Ate all lunch, drank water well.",
    naps: "Rested 45 minutes.",
    notes: "Alya helped a friend tidy up — great sharing today!",
    skills: ["Sharing", "Listening", "Fine motor"],
  },
  {
    id: "r2",
    studentId: "s1",
    teacherId: "t3",
    date: "2026-07-11",
    title: "Weekly progress",
    mood: "ok",
    activities: "Art station painting, bilingual songs, block building.",
    meals: "Ate half of lunch.",
    naps: "Did not nap, quiet reading instead.",
    notes: "A bit quieter than usual but engaged in art.",
    skills: ["Creativity", "Vocabulary"],
  },
  {
    id: "r3",
    studentId: "s2",
    teacherId: "t3",
    date: "2026-07-18",
    title: "Weekly progress",
    mood: "happy",
    activities: "Science water play, counting games, music.",
    meals: "Finished snack and lunch.",
    naps: "Slept 60 minutes.",
    notes: "Kenzo counted to 20 confidently!",
    skills: ["Counting", "Curiosity"],
  },
  {
    id: "r4",
    studentId: "s5",
    teacherId: "t4",
    date: "2026-07-18",
    title: "Weekly progress",
    mood: "happy",
    activities: "Phonics, group project on animals, PE.",
    meals: "Ate well.",
    naps: "N/A (kindergarten)",
    notes: "Sofia led her group presentation.",
    skills: ["Leadership", "Phonics", "Teamwork"],
  },
  {
    id: "r5",
    studentId: "s9",
    teacherId: "t4",
    date: "2026-07-18",
    title: "Weekly progress",
    mood: "happy",
    activities: "Science experiment, reading buddies, outdoor games.",
    meals: "Finished lunch and fruit snack.",
    naps: "N/A (kindergarten)",
    notes: "Rafi helped a younger friend tie shoelaces — so proud!",
    skills: ["Kindness", "Curiosity", "Reading"],
  },
  {
    id: "r6",
    studentId: "s1",
    teacherId: "t3",
    date: "2026-09-18",
    title: "Laporan minggu ini",
    mood: "happy",
    activities: "Puzzle huruf, jalan sehat, cerita bilingual.",
    meals: "Makan siang habis, minum air cukup.",
    naps: "Istirahat 40 menit.",
    notes: "Alya aktif membantu teman menyusun puzzle.",
    skills: ["Kerjasama", "Kosakata", "Motorik kasar"],
  },
  {
    id: "r7",
    studentId: "s1",
    teacherId: "t3",
    date: "2026-09-23",
    title: "Catatan harian",
    mood: "happy",
    activities: "Hari berbagi mainan, kolase geometri, circle time.",
    meals: "Snack buah & makan siang penuh.",
    naps: "Tidak tidur, membaca buku tenang.",
    notes: "Hari ini Alya menunggu giliran dengan sabar.",
    skills: ["Kesabaran", "Berbagi"],
  },
  {
    id: "r8",
    studentId: "s9",
    teacherId: "t4",
    date: "2026-09-23",
    title: "Catatan harian",
    mood: "happy",
    activities: "Surat untuk orang tua, percobaan bayangan.",
    meals: "Makan siang selesai.",
    naps: "N/A (kindergarten)",
    notes: "Rafi menulis namanya sendiri di kartu!",
    skills: ["Menulis", "Percaya diri"],
  },
];

export const financeSummaries: FinanceSummary[] = [
  {
    month: "2026-07",
    tuitionCollected: 8100000,
    tuitionPending: 7500000,
    eventFees: 300000,
    expenses: 4200000,
  },
  {
    month: "2026-06",
    tuitionCollected: 19600000,
    tuitionPending: 0,
    eventFees: 350000,
    expenses: 5100000,
  },
  {
    month: "2026-05",
    tuitionCollected: 18800000,
    tuitionPending: 2500000,
    eventFees: 1000000,
    expenses: 6800000,
  },
  {
    month: "2026-08",
    tuitionCollected: 16200000,
    tuitionPending: 2800000,
    eventFees: 450000,
    expenses: 4900000,
  },
  {
    month: "2026-09",
    tuitionCollected: 9800000,
    tuitionPending: 5300000,
    eventFees: 200000,
    expenses: 3100000,
  },
];

export const kasEntries: KasEntry[] = [
  {
    id: "k1",
    date: "2026-07-01",
    type: "in",
    account: "bank",
    source: "tuition",
    amount: 5300000,
    note: "Tuition July — bank / transfer",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "k1b",
    date: "2026-07-01",
    type: "in",
    account: "cash",
    source: "tuition",
    amount: 2800000,
    note: "Tuition July — tunai",
    recordedBy: "Rina Wijaya",
    tuitionId: "tu5",
  },
  {
    id: "k2",
    date: "2026-07-05",
    type: "in",
    account: "bank",
    source: "donation",
    amount: 5000000,
    note: "Alumni parent fund — playground mats",
    recordedBy: "Maya Santoso",
  },
  {
    id: "k3",
    date: "2026-07-08",
    type: "in",
    account: "cash",
    source: "gift",
    amount: 1500000,
    note: "Cash gift for library books",
    recordedBy: "Maya Santoso",
  },
  {
    id: "k4",
    date: "2026-07-10",
    type: "in",
    account: "bank",
    source: "sponsor",
    amount: 3000000,
    note: "Local bakery sponsor for snack week",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "k5",
    date: "2026-07-12",
    type: "out",
    account: "bank",
    source: "expense",
    amount: 3200000,
    note: "July operating expenses (transfer)",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "k5b",
    date: "2026-07-12",
    type: "out",
    account: "cash",
    source: "expense",
    amount: 1000000,
    note: "Petty cash — supplies",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "k6",
    date: "2026-07-15",
    type: "in",
    account: "bank",
    source: "event",
    amount: 300000,
    note: "Event fee deposits",
    recordedBy: "Dewi Kartika",
  },
  {
    id: "k7",
    date: "2026-06-28",
    type: "in",
    account: "bank",
    source: "donation",
    amount: 2000000,
    note: "Anonymous community donation",
    recordedBy: "Maya Santoso",
  },
  {
    id: "k8",
    date: "2026-06-04",
    type: "in",
    account: "cash",
    source: "tuition",
    amount: 2500000,
    note: "Tuition June — Kenzo (tunai)",
    recordedBy: "Dewi Kartika",
    tuitionId: "tu9",
  },
  {
    id: "k9",
    date: "2026-09-02",
    type: "in",
    account: "bank",
    source: "tuition",
    amount: 2500000,
    note: "SPP Agustus — Alya (transfer)",
    recordedBy: "Maya Santoso",
    tuitionId: "tu16",
  },
  {
    id: "k10",
    date: "2026-09-18",
    type: "out",
    account: "cash",
    source: "expense",
    amount: 450000,
    note: "ATK & cat kegiatan seni",
    recordedBy: "Rina Wijaya",
  },
  {
    id: "k11",
    date: "2026-09-22",
    type: "in",
    account: "bank",
    source: "donation",
    amount: 1500000,
    note: "Donasi orang tua — peralatan bermain",
    recordedBy: "Maya Santoso",
  },
  {
    id: "k12",
    date: "2026-09-23",
    type: "out",
    account: "cash",
    source: "expense",
    amount: 275000,
    note: "Snack bersama & stiker kelas",
    recordedBy: "Dewi Kartika",
  },
];

export function getKasBalance(
  entries: KasEntry[] = kasEntries,
  account?: "cash" | "bank",
): number {
  return entries
    .filter((e) => (account ? e.account === account : true))
    .reduce((sum, e) => sum + (e.type === "in" ? e.amount : -e.amount), 0);
}

export function getKasBalances(entries: KasEntry[] = kasEntries) {
  return {
    cash: getKasBalance(entries, "cash"),
    bank: getKasBalance(entries, "bank"),
    total: getKasBalance(entries),
  };
}

/** Demo parent session — Sari Rahman has Alya (s1) + Rafi (s9) */
export const currentParentChildIds = ["s1", "s9"];
export const currentParentChildId = currentParentChildIds[0];
export const currentParentName = "Sari Rahman";

export function getStudent(id: string) {
  return students.find((s) => s.id === id);
}

export function getStudentsByParentEmail(email: string) {
  return students.filter((s) =>
    s.parents.some((p) => p.email.toLowerCase() === email.toLowerCase()),
  );
}

export function getClass(id: string) {
  return classes.find((c) => c.id === id);
}

export function getTeacher(id: string) {
  return teachers.find((t) => t.id === id);
}

export function getEvent(id: string) {
  return events.find((e) => e.id === id);
}

export function studentsInClass(classId: string) {
  return students.filter((s) => s.classId === classId && s.status === "active");
}
